---
- name: Install Java 11 and Maven
  hosts: jenkins-slave
  become: yes  # Run tasks as a privileged user (e.g., sudo)

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Set Java environment variables (adjust as needed)
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
   

   